// Code generated by protoc-gen-go.
// source: packet.proto
// DO NOT EDIT!

/*
Package packet is a generated protocol buffer package.

It is generated from these files:
	packet.proto

It has these top-level messages:
	Timestamp
	Packet
	Status
*/
package packet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// A Timestamp represents a UTC time.
type Timestamp struct {
	// Represents seconds of UTC time since Unix epoch.
	Seconds int64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	// Represents nanosecond offset from seconds.
	Nanos int32 `protobuf:"varint,2,opt,name=nanos" json:"nanos,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// A Packet is a single bundle of data of a single type from a single device.
type Packet struct {
	// serial represents the serial number of the device.
	Serial int64 `protobuf:"varint,1,opt,name=serial" json:"serial,omitempty"`
	// time represents the timestamp of the first datapoint.
	Time *Timestamp `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	// delta represents the nanosecond time delta between data points.
	Delta int64 `protobuf:"varint,3,opt,name=delta" json:"delta,omitempty"`
	// type represents the data type. Must be a single character.
	Type string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	// device represents the name of the device. Optional.
	Device string `protobuf:"bytes,5,opt,name=device" json:"device,omitempty"`
	// data represents the data points.
	Data []int64 `protobuf:"zigzag64,6,rep,packed,name=data" json:"data,omitempty"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Packet) GetTime() *Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

// A Status represents the status of an RPC.
type Status struct {
	// success represents whether or not the RPC was successful. True means that it was, false means that it was not.
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	// msg is an optional error message.
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Timestamp)(nil), "Timestamp")
	proto.RegisterType((*Packet)(nil), "Packet")
	proto.RegisterType((*Status)(nil), "Status")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for LandingZone service

type LandingZoneClient interface {
	// SendPacket stores a Packet in the database.
	SendPacket(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*Status, error)
}

type landingZoneClient struct {
	cc *grpc.ClientConn
}

func NewLandingZoneClient(cc *grpc.ClientConn) LandingZoneClient {
	return &landingZoneClient{cc}
}

func (c *landingZoneClient) SendPacket(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/LandingZone/SendPacket", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LandingZone service

type LandingZoneServer interface {
	// SendPacket stores a Packet in the database.
	SendPacket(context.Context, *Packet) (*Status, error)
}

func RegisterLandingZoneServer(s *grpc.Server, srv LandingZoneServer) {
	s.RegisterService(&_LandingZone_serviceDesc, srv)
}

func _LandingZone_SendPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Packet)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(LandingZoneServer).SendPacket(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _LandingZone_serviceDesc = grpc.ServiceDesc{
	ServiceName: "LandingZone",
	HandlerType: (*LandingZoneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPacket",
			Handler:    _LandingZone_SendPacket_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x3c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x14, 0x84, 0x49, 0x93, 0x38, 0xe4, 0x95, 0xa1, 0xb2, 0x10, 0xb2, 0x18, 0x50, 0x94, 0xa9, 0x53,
	0x90, 0x0a, 0x1b, 0x1b, 0x33, 0x03, 0x72, 0x99, 0xd8, 0x8c, 0xfd, 0x54, 0x45, 0x34, 0x76, 0x54,
	0xbb, 0x48, 0xfc, 0x15, 0x7e, 0x2d, 0xce, 0x73, 0xd2, 0xed, 0xbe, 0x93, 0xee, 0x9e, 0xcf, 0x70,
	0x33, 0x2a, 0xfd, 0x8d, 0xa1, 0x1b, 0x4f, 0x2e, 0xb8, 0xf6, 0x05, 0xea, 0x8f, 0x7e, 0x40, 0x1f,
	0xd4, 0x30, 0x72, 0x01, 0x95, 0x47, 0xed, 0xac, 0xf1, 0x22, 0x6b, 0xb2, 0x6d, 0x2e, 0x17, 0xe4,
	0xb7, 0x50, 0x5a, 0x65, 0x9d, 0x17, 0xab, 0xe8, 0x97, 0x32, 0x41, 0xfb, 0x97, 0x01, 0x7b, 0xa7,
	0x36, 0x7e, 0x07, 0xcc, 0xe3, 0xa9, 0x57, 0xc7, 0x39, 0x39, 0x13, 0x7f, 0x80, 0x22, 0xc4, 0x7e,
	0xca, 0xad, 0x77, 0xd0, 0x5d, 0x8e, 0x49, 0xf2, 0xa7, 0x62, 0x83, 0xc7, 0xa0, 0x44, 0x4e, 0xb1,
	0x04, 0x9c, 0xc7, 0xd4, 0xef, 0x88, 0xa2, 0x88, 0x66, 0x2d, 0x49, 0x4f, 0x17, 0x0c, 0xfe, 0xf4,
	0x1a, 0x45, 0x49, 0xee, 0x4c, 0xd1, 0x2f, 0x8c, 0x8a, 0x05, 0xac, 0xc9, 0xb7, 0xfc, 0x75, 0xb5,
	0xc9, 0x24, 0x71, 0xfb, 0x0c, 0x6c, 0x1f, 0x54, 0x38, 0x7b, 0x9a, 0x75, 0xd6, 0x1a, 0x7d, 0x9a,
	0x75, 0x2d, 0x17, 0xe4, 0x1b, 0xc8, 0x07, 0x7f, 0xa0, 0xc7, 0xd5, 0x72, 0x92, 0xbb, 0x47, 0x58,
	0xbf, 0x29, 0x6b, 0x7a, 0x7b, 0xf8, 0x74, 0x16, 0x79, 0x03, 0xb0, 0x47, 0x6b, 0xe6, 0x91, 0x55,
	0x97, 0xc4, 0x7d, 0xd5, 0xa5, 0xea, 0xf6, 0xea, 0x8b, 0xd1, 0x3f, 0x3e, 0xfd, 0x07, 0x00, 0x00,
	0xff, 0xff, 0xfc, 0xf0, 0x16, 0xa5, 0x57, 0x01, 0x00, 0x00,
}
