language: go
go:
  - tip
sudo: required
dist: trusty
env:
  global:
    - BACKEND="$HOME/gopath/src/github.com/seadsystem/Backend"
    - API="$BACKEND/DB/api"
    - LZONE="$BACKEND/DB/landingzone"
    - ACTIVATE="venv/bin/activate"
addons:
  apt:
    packages:
    - python3
    - libpq-dev
    - python3-numpy
    - python3-matplotlib
    - python3-coverage

install:
  - go get github.com/olt/libpq
  - go get github.com/DATA-DOG/go-sqlmock
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - sudo apt-get install -y python3-pip
  - cd "$API"; virtualenv -p python3 venv
  - cd "$API"; source $ACTIVATE && pip3 install --upgrade pip
  - cd "$API"; source $ACTIVATE && pip3 install psycopg2
  - cd "$API"; source $ACTIVATE && pip3 install numpy
  - cd "$API"; source $ACTIVATE && pip3 install matplotlib
  - cd "$API"; source $ACTIVATE && pip3 install codecov
before_script:
  - go vet "$LZONE/..."
script:
  - cd "$LZONE"; go install
  - cd "$API"; source $ACTIVATE && coverage run -m unittest discover
after_success:
  - cd "$BACKEND"; go test "$LZONE/..."
  - cd "$LZONE"; ./test-coverage.sh
  - cd "$API"; source $ACTIVATE && codecov
