sudo: required
dist: trusty

language: go

go:
  - 1.6
  - tip

env:
  global:
    - BACKEND="$HOME/gopath/src/github.com/seadsystem/Backend"
    - API="$BACKEND/DB/api"
    - LZONE="$BACKEND/DB/landingzone"

addons:
  apt:
    packages:
    - libpq-dev
    - python3-numpy
    - python3-matplotlib
    - python3-coverage
    - python3-psycopg2

install:
  - go get github.com/olt/libpq
  - go get github.com/DATA-DOG/go-sqlmock
  - go get github.com/axw/gocov/gocov
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/codecov/example-go
  - pyenv global 3.4
  - python3 -V
  - sudo apt-get install -y python3-pip
  - pip3 install --user coveralls

before_script:
  - cd "$LZONE"; go install

script:
  - go vet "$LZONE/..."
  - cd "$BACKEND"; go test "$LZONE/..."
  - cd "$API"; python3-coverage run --include="$API/*.py" -m unittest discover

after_success:
  - "$GOPATH/src/github.com/codecov/example-go/go.test.sh"
  - bash <(curl -s https://codecov.io/bash)
  - coveralls