# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Vagrantfile for SEAD DB Server
#
# Port Forwarding:
#    8080     Python API
#    9000     Go Landing Zone
#
# Provisioning:
#    * Package updates and git using apt
#    * Configure users, install PostgreSQL 9.4 and Go with libpq module via puppet
#    * Deploy landingzone and seadapi using deploy.sh script
#
# Shared Folders:
#    * puppet => /etc/puppet 
#
#

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 9000, host: 9000

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true
  # config.ssh.username = "username"
  # config.ssh.private_key_path = "~/.ssh/id_rsa"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder "puppet", "/etc/puppet"

  # Update
  config.vm.provision 'shell' do |shell|
     shell.inline = 'apt-get update && apt-get dist-upgrade -y && apt-get install -y git'
  end

  # Provision the server via puppet
  config.vm.provision "puppet" do |puppet|
     puppet.manifests_path = "puppet/manifests"
     puppet.module_path = "puppet/modules"
     puppet.manifest_file  = "site.pp"
  end
end
